doc/Sphinx/namelist.rst
ExtField has `field` instead of `fields` and also doesn't allow lists in it.
=> ExtField incorrect example

src/Profiles/Function.cpp, src/Profiles/Function.h, src/Profiles/Profile.cpp, src/Python/pyprofiles.py
I propose to add a temporal profile that is very useful for several simulations:
`tsin2plateau`, a sin2 profile with the option to become flattop profile with sin2 ramps.
I used the code that Micka and Anna developed some time ago and I refactored it.
I changed the default values: if only one parameters is given (`fwhm`) the profile is similar to a Gaussian profile having fwhm (of the field amplitude) defined by the user.
If `plateau` is also given, a plateau is added splitting in two the previous profile.
If the user defines `slope1` and/or `slope2`, he/she controls the width of the sin2 ramps at the beginning and at the end of the profile. 
See attachment.
Someone might not like the redundancy of `fwhm`, `slope1`, `slope2`.
`slope1`, `slope2` use `fwhm` as default value. If they both …
=> add new temporal profile tsin2plateau

src/Params/Params.cpp
This typo was introduced when `east` and `west` were renamed to `xmax` and `xmin`.
=> Params.cpp - typo lxmax -> least

src/Python/pyinit.py
Caused a python error in time profiles (see ``pyprofiles.py``) which require the ``simulation_time`` to be always defined.
=> fix simulation_time when defined through number_of_timesteps

src/Python/pyprofiles.py
It seems that the formula for a three-dimensional Gaussian beam's laser amplitude was used for the two-dimensional lasers as well. For a two-dimensional Gaussian beam the electric field amplitude falls as the square root of beam radius, as per [Eq. (2.30) here](http://www.phys.ncku.edu.tw/~cctsai/teaching/10202/gaussian%20beam%20derive.pdf).
I have conducted some tests to verify that the problem is real and that these changes fix it, using the following namelist:
```python
from numpy import pi
l0 = 2.*pi                      # laser wavelength
t0 = l0	                        # optical cycle
Lsim = [800*l0,300.*l0]         # length of the simulation
Tsim = 1500.*t0			# duration of the simulation
resx = 16.                       # nb of cells in on laser wavelength
rest = 48. …
```
=> Fix LaserGaussian2D amplitude problem

scripts/CompileTools/machine/marconi_knl_intel
CINECA Marconi KNL intel compilation script is fixed (instrucions have been updated to intel-2018).
=> Marconi KNL compilation script now works

scripts/CompileTools/machine/marconi_knl_intel
Found a cleaner way to compile on CINECA - MARCONI. It still requires exporting manually "SMILEICXX=mpiicpc".
=> Fixed KNL Marconi compilation

scripts/CompileTools/machine/marconi_knl_intel
Now Smilei can be compiled on MARCONI (KNL) with just the `machine=marconi_knl_intel` option when calling make. No more manual exports are required.
=> Marconi knl compilation script updated

doc/Sphinx/collisions.rst
This pull request fixes a [DOI](https://en.wikipedia.org/wiki/Digital_object_identifier) in the documentation of the collisions in `Smilei`. The Frankel 1979 PRA had the DOI of a Sentoku paper from 1998. Since the Sentoku paper also describes collisions, referencing it might be needed too (another Sentoku paper was already cited).
- Sentoku 1998 (current DOI): http://dx.doi.org/10.1143/JPSJ.67.4084
- Frankel 1979 PRA (fixed DOI): https://doi.org/10.1103/PhysRevA.20.2120
=> fix DOI in documentation collisions

src/Diagnostic/DiagnosticTrack.cpp
`unsigned long long` particle id assigned to `unsigned int`.
`id` is not necessary here and is deleted.
=> Serious assignment error in track particles

doc/Sphinx/post-processing.rst, happi/_Diagnostics/Diagnostic.py, happi/_Diagnostics/Field.py, happi/_Diagnostics/ParticleBinning.py, happi/_Diagnostics/Performances.py, happi/_Diagnostics/Probe.py, happi/_Diagnostics/Scalar.py, happi/_Utils.py
Some minor changes to happi to improve the user experience somewhat (and small bug fixes for some probe diagnostics and the transparent option):
* 2D (image) plots can accept the `norm` kwarg now, enabling log plots with nice colorbars along with more unusual normalisations like power laws and symmetric log
* An argument `vsym` that lets the range of a color axis vary automatically according to the data being plotted (e.g. in an animation) but forces it to remain centred on zero
* Nicer behaviour of colorbars: they now fit to the height of the plot instead of changing their relative size as the window changes size, have settable labels (useful for multiPlot) and width/padding. Default padding isn't currently auto-adjusted for multiPlot instances to stop overlab of one colorbar with the …
=> Happi Quality-of-Life changes

happi/_Utils.py
Documentation for happi.multiPlot states the following:-
> One diagnostic may have the option side="right" to use the right-hand-side axis.
Attempting to use this functionality results in the following stack trace and produces an empty plot:-
```
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/path/to/Smilei/happi/_Utils.py", line 625, in multiPlot
mp = _multiPlotUtil( *Diags, **kwargs )
File "/path/to/Smilei/happi/_Utils.py", line 502, in __init__
self.bothsides = any(rightside) and not allright
NameError: name 'allright' is not defined
```
This small PR resolves this and restores the functionality.
=> fix(happi): multiplot y-axis right side plotting

src/Patch/VectorPatch.cpp, src/Patch/VectorPatch.h, src/Python/pyinit.py, src/Species/Species.cpp, src/Species/Species.h, src/Species/SpeciesFactory.h
In this branch a bug fix for Issue #420 is implemented. The changes perform a safer check on the time when relativistic Poisson's solver must be called for a given `Species` with relativistic initialization enabled (a check on an int instead of a float).
=> Time relativistic poisson solver

scripts/compile_tools/machine/archer2
Added machine script for compilation on [ARCHER2](https://www.archer2.ac.uk/). Tested with the following simulations on the ARCHER2-4c service:
- `tst1d_02_two_str_instability`
- `tst2d_04_laser_wake.py`
- An extended 2D LWFA simulation with  high resolution (40 cells per laser wavelength, 512 particles per cell, 8 nodes).
- Other physical benchmarks against known results from the EPOCH PIC code.
I've not yet been able to test vectorisation, but there may be some subtlety getting things running smoothly with the AMD chips.
Side note: I ran some performance benchmarks, and the optimal thread/process/patch configuration is currently unclear to me. I would expect peak performance when the number of MPI processes per node matches the number of NUMA regions per node (8), but this is not the …
=> Added ARCHER2 machine script

src/Interpolator/Interpolator3D2OrderV.cpp
The interpolation for Ex is (dual, primal, primal), so `coeffxp` should be `coeffxd` instead.
=> Corrected an interpolation coefficient

src/Tools/backward.hpp
Tested compiling for Apple macOS Monterey. This is similar to https://github.com/bombela/backward-cpp/issues/200
=> Add compilation support for Apple M1 chips

.github/workflows/sphinx-build.yml, .github/workflows/sphinx.yml, happi/_Diagnostics/TrackParticles.py
This provides a ~10% perf improvement on the PALLAS workload that I've been profiling previously (see #622)
=> Avoid redundant h5py calls in TrackParticles' _init()

scripts/compile_tools/machine/archer2
Hi,
I'm a member of the CSE team for ARCHER2, one of our users has asked for instructions on how to install Smilei on our system after our [software upgrade](https://docs.archer2.ac.uk/faq/upgrade-2023/), so I've taken the opportunity to update your compilation script -- thank you for providing this, by the way.
Cray's python module was changed to support python 3.9, and it is now [much simpler to add packages](https://docs.archer2.ac.uk/user-guide/python/#installing-your-own-python-packages-with-pip) on top of the system installation.
I've removed a couple of the exports, since the `module load cray-python` action already does the same, and I added a new export to the job script that passes the value of `SLURM_CPUS_PER_TASK` to `SRUN`, since it [doesn't inherit it by default …
=> Updated compilation instructions for ARCHER2

scripts/compile_tools/machine/archer2
Continuing from #635, the module `epcc-job-env` does not exist anymore, so it needs to be removed from the example job script.
=> Removing non-existent module from example job script

doc/Sphinx/implementation.rst
fix typos in the sphinx documentation I found while reading.
=> fix documentation typos
